### ISSUE TITLE
Building the war file

### ISSUE THREAD

**Issue by trapperkeeper** [EBISPOT/urigen#7]
I have been using URIGen for some time, but haven't needed to tweak the configuration is quite a while. Now that I do, I am realizing that I cannot (Mozilla Persona login is no longer alive). In an attempt to update, I am trying to grab the updated server code, with the updated authentication. I have cloned the repo and performed a "mvn clean install", but it does not build the war file. The webapp directory does not contain the dependency libraries and compiled class files. Is there an easy way to build the war file that I am missing? Or do I need to assemble the bits by hand?

**Comment by simonjupp** [comment]
what error did you get? It just built for me when I tried it.

**Comment by trapperkeeper** [comment]
I didn't get an error, but no war file was produced. I get a urigen.jar file in urigen-core/target. But I don't get a container ready package. Should I?

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for UriManager 2.0-SNAPSHOT:
[INFO] 
[INFO] UriManager ......................................... SUCCESS [  4.274 s]
[INFO] urigen-core ........................................ SUCCESS [ 11.788 s]
[INFO] urigen-protege-plugin .............................. SUCCESS [  9.201 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.912 s
[INFO] Finished at: 2019-02-08T10:06:27-08:00
[INFO] ------------------------------------------------------------------------

**Comment by simonjupp** [comment]
I'm not sure why @matthewhorridge changed the packaging from war to jar, anyway I reverted this back to war and I can run and deploy this in jetty. 

https://github.com/EBISPOT/urigen/commit/7cc93bd2d36fa1308856c0be10040fa6442ffbd7#diff-e017072c7459365b43ce163cdf2101d7L11

**Comment by trapperkeeper** [comment]
Excellent! Thanks Simon, I will give it a try.

**Comment by matthewhorridge** [comment]
Don't remember exactly why I changed it, but I think it's because there's a dependency on the core from the protege plugin and this won't work as a war.  That's my guess.  Really, urigen-core should be a library and then the web app should be built by a module that depends on the core.
